version: "3.9"
services:
  server:
    build:
      context: sources/server
    ports:
      - 7000:7000
      - 8000:8000
    networks:
      - app_network
  redis:
    image: redis:alpine
    networks:
      - app_network

networks:
  app_network: